"""Reports router — generates downloadable CSV analysis reports.

Endpoints:
    GET /api/reports/download?period=weekly|monthly|yearly
"""

import csv
import io
from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from models.database import get_db
from models.entities import AnalyzedEmail
from routers.auth import get_current_user

router = APIRouter()

_PERIOD_DAYS = {"weekly": 7, "monthly": 30, "yearly": 365}


@router.get("/reports/download")
def download_report(
    period: str = Query("weekly", pattern="^(weekly|monthly|yearly)$"),
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> StreamingResponse:
    """Generate a CSV report of analyzed emails for the given period.

    Args:
        period: One of weekly, monthly, yearly.
        current_user: Authenticated user from JWT.
        db: Database session.

    Returns:
        Streaming CSV file download.
    """
    days = _PERIOD_DAYS[period]
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)

    rows = (
        db.query(AnalyzedEmail)
        .filter(
            AnalyzedEmail.user_id == current_user["sub"],
            AnalyzedEmail.analyzed_at >= cutoff,
        )
        .order_by(AnalyzedEmail.analyzed_at.desc())
        .all()
    )

    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "Date", "Sender", "Subject", "Risk Score", "Risk Tier", "Snippet",
    ])

    high = med = low = 0
    for r in rows:
        date_str = r.analyzed_at.strftime("%Y-%m-%d %H:%M") if r.analyzed_at else ""
        writer.writerow([
            date_str,
            r.sender or "Unknown",
            r.subject or r.body[:80] if r.body else "No subject",
            r.risk_score,
            r.risk_tier,
            (r.body[:200] if r.body else "")
                .replace("\n", " ").replace("\r", " "),
        ])
        if r.risk_tier == "High":
            high += 1
        elif r.risk_tier == "Medium":
            med += 1
        else:
            low += 1

    writer.writerow([])
    writer.writerow(["SUMMARY"])
    writer.writerow(["Period", f"Last {days} days ({period})"])
    writer.writerow(["Generated", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")])
    writer.writerow(["Generated By", current_user.get("sub", "unknown")])
    writer.writerow(["Total Emails", len(rows)])
    writer.writerow(["High Risk", high])
    writer.writerow(["Medium Risk", med])
    writer.writerow(["Low Risk", low])

    buf.seek(0)
    filename = f"psychshield_{period}_report_{datetime.now(timezone.utc).strftime('%Y%m%d')}.csv"

    return StreamingResponse(
        iter([buf.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
